### ISSUE TITLE
make data count setup

### ISSUE THREAD

**Issue by jt14den** [ucla-data-archive/dataverse-ansible#91]

**Comment by jmjamison** [comment]
Installed and run manually on test.dataverse.  Next setup to run as cron job.

**Comment by jmjamison** [comment]
1) Set up on test.dataverse and running with nightly (1am) crontab.    
2) Install on production.dataverse, run manually and setup for crontab (1am) 
3) sent email to datacite.org to request  JSON Web Token (JWT)

**Comment by jmjamison** [comment]
I've installed the counter process on production dataverse and setup a crontab script to run at night.   

Next I have to contact datacite to get a json web token so I can sent usage metrics (views, downloads) to the datacite hub.
Datacite people still need an email and client id from me.

**Comment by jmjamison** [comment]
Waiting to hear back from datacite.

**Comment by jmjamison** [comment]
Received the test web token from Kelly / datacite.  I need to read through what she sent and will try with the test info. (That is, test it on production dataverse.)

**Comment by jmjamison** [comment]
Just found a python error in the script to run make-data-count run at night.  I'm trying to figure out when/how it was introduced.  

Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import config
  File "/usr/local/counter-processor-0.0.1/config/__init__.py", line 1, in <module>
    from .config import *
  File "/usr/local/counter-processor-0.0.1/config/config.py", line 74, in <module>
    setattr(thismodule, x, cfg[x])
TypeError: string indices must be integers
./run_mdc.sh: line 22: /home/counter: Is a directory

First ones are just warnings, depreciated code.  Last one, there is no line 22.   

Going back to test system to compare and see if I can figure out what happened.

**Comment by jmjamison** [comment]
Corresponding with Dataverse developers I learned that the counter-processor script, as-is does **not** collect the DOIs for sub-dataverses (ie. the file level DOIs).   But they wrote a script to collect this information and add it to the report.

1)   It's not documented that counter-processor doesn't collect the sub-dataverses/file level DOIs.
2)  Not sure if the script is public yet - I was directed to an issue and it may be public and documented in version 5.0.

**Comment by jmjamison** [comment]
Right now the counter-processor part work with no trouble, nightly cron job.  The blocker is the part about citations. Waiting to hear back from someone at CDL.

**Comment by jt14den** [comment]
@jmjamison cool! Almost there.

**Comment by jt14den** [comment]
How is this going? @jmjamison

**Comment by jmjamison** [comment]
File view and downloads works.  Though keep in mind that the counter-processor is only intended for datasets not individual files.  Dataverse people know about it and have a work-around.
For the rest - getting citations I'm still trying to get ahold of the part-time person that Daniella Lowenberg has refered me to. I have to start another round of emailing.

**Comment by jmjamison** [comment]
I will be meeting with Rushiraj Nenuji and possibly Daniella, this week to work out how the citations are managed.  This issue should be close-able after the meeting.

**Comment by jmjamison** [comment]
I've requested the official JSON Web Token.  

Question:  do we have a datasite account.  Need to check.

**Comment by jt14den** [comment]
CDL is a member of datacite, we proxy thru CDL to get our DOIs, so whatever token we'd need should be apart of that account. Let me know if we need to ping Daniella.

**Comment by jmjamison** [comment]
Need to verify what UCLA's repository id is.   Is it CDL.UCLA?   Emailed both Daniella and Maria (Gould).

**Comment by jmjamison** [comment]
I've add the DataCite web token to dataverse production.    Next I have to write a python script to get a report of any citations - using the api.
